Weekend/homework
lenzloesche/neue-fische-own-website pull request #1
Opened 2023-01-27 17:12 UTC by lenzloesche

# things I have done:
- I added a README.md
- I made it responsive.

I don't know what else to do with this website. :)

2023-01-29 18:47 UTC, sahedw commented
just downloaded the files and looks good! Nice job :)

2023-01-30 07:38 UTC, nikokreissl approved these changes
Nothing to add from my side, good job. :)

2023-01-30 11:10 UTC, actyralf requested changes
Hey Lenz,

great job!

I have some comments regarding the initial commit - I can't do this line by line because the affected lines are not part of the pull request.

Here they are:

- Consider to use a `ul` with `li`s for the navbar for accessibility reasons 
- Consider to use `<section>` tags instead of `<div>` where feasible
- Make sure that all your images have an appropriate `alt` attribute
- Make sure your inputs have corresponding labels: You have a label for your e-mail field, but it's not linked to the input
- JS: `calculate` is not a good name for the variable holding the progress percentage. You should use verbs only for functions. Consider to use sth. like `progressPercentage` or similar.
- JS: You should link the `.js` file with the `defer` attribute to ensure that HTML/CSS is completely loaded before JS gets executed.
- We want to develop mobile first, so please do your default layout for mobile and your media queries for `min-width` instead of `max-width`
- Don't use `<a>` tags with empty `href` attribute
- You used `<h3>` tags to wrap you nav items. Consider selecting the nav items with an appropriate CSS selector and style them via this selector. `<h3>` should be reserved for headings.

2023-02-03 10:42 UTC, actyralf approved these changes
Hey Lenz,

great job! I left a few tiny comments - feel free to merge anyhow and maybe consider them for the next PR. Alternatively you can fix them right now but you don't have to request another review for the fix.

2023-02-03 10:42 UTC, actyralf commented on index.html
> +        <div class="nav__arrow" id="arrow">
You should have only `<li>` tags inside your list. Please wrap the `<div>` inside an `<li>`

2023-02-03 10:42 UTC, actyralf commented on index.html
>      <header></header>
`<header>` is empty - you could wrap your nav inside it...

2023-02-03 10:42 UTC, actyralf commented on index.html
> +        <div class="skill">
semantically this looks like a list - please consider to use `<ul>` instead of `<div>`

2023-02-03 10:42 UTC, actyralf commented on index.html
> +        align="center"
The `align` attribute is deprecated (https://www.w3.org/TR/html401/present/graphics.html).
Please use the CSS `text-align` property to achieve the effect.

2023-02-03 11:19 UTC, merged